# fonts
.local/share/fonts/JetBrains Mono Regular Nerd Font Complete.ttf:
  type: file
  url: 'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete.ttf'
  refreshPeriod: 168h

.local/share/fonts/JetBrains Mono Regular Nerd Font Complete Mono.ttf:
  type: file
  url: 'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete%20Mono.ttf'
  refreshPeriod: 168h

.local/share/fonts/JetBrains Mono Italic Nerd Font Complete.ttf:
  type: file
  url: 'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/Italic/complete/JetBrains%20Mono%20Italic%20Nerd%20Font%20Complete.ttf'
  refreshPeriod: 168h

.local/share/fonts/JetBrains Mono Italic Nerd Font Complete Mono.ttf:
  type: file
  url: 'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/Italic/complete/JetBrains%20Mono%20Italic%20Nerd%20Font%20Complete%20Mono.ttf'
  refreshPeriod: 168h

.local/share/fonts/JetBrains Mono Bold Nerd Font Complete.ttf:
  type: file
  url: 'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/Bold/complete/JetBrains%20Mono%20Bold%20Nerd%20Font%20Complete.ttf'
  refreshPeriod: 168h

.local/share/fonts/JetBrains Mono Bold Nerd Font Complete Mono.ttf:
  type: file
  url: 'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/Bold/complete/JetBrains%20Mono%20Bold%20Nerd%20Font%20Complete%20Mono.ttf'
  refreshPeriod: 168h

.local/share/fonts/JetBrains Mono Bold Italic Nerd Font Complete.ttf:
  type: file
  url: 'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/BoldItalic/complete/JetBrains%20Mono%20Bold%20Italic%20Nerd%20Font%20Complete.ttf'
  refreshPeriod: 168h

.local/share/fonts/JetBrains Mono Bold Italic Nerd Font Complete Mono.ttf:
  type: file
  url: 'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/BoldItalic/complete/JetBrains%20Mono%20Bold%20Italic%20Nerd%20Font%20Complete%20Mono.ttf'
  refreshPeriod: 168h
  